---
title: "Step 5. Standardize Condition indicators"
format: html
---
Following the equation for Step 3 (below), each standardized condition value was calculated and can be found in [Table 5](#table5).

$$
SI_0 = \frac{I_0}{RV}
$$

Where:

-   $SI_0$ = Standardized Condition Indicator at project start

-   $I_0$ = Condition indicator value at project start

-   $RV$ = Reference value

Species richness of herpetofauna: $$ 
    SI_{0,\text{herp}} = \frac{46}{90} = 0.511
    $$

Species richness of birds: $$
SI_{0,\text{birds}} = \frac{215}{230} = 0.935
$$

Species richness of mammals: $$
SI_{0,\text{mammals}} = \frac{31}{46} = 0.674
$$

Aboveground biomass: $$
SI_{0,\text{AGB}} = \frac{152.051}{187.234} = 0.812
$$

Forest canopy cover: $$
SI_{0,\text{canopy}} = \frac{60}{72} = 0.833
$$

<details open>

<summary><strong>[Table 5](#table5). Standardized Condition Indicators</strong></summary>

::: {#table5 .terra-exec}
| Condition Component | Indicator Description | Reference Value | Condition Value Measured at Project Start | Standardized Condition Value |
|:--------------|:--------------|--------------:|--------------:|--------------:|
| Composition (Cm1) | Species richness of herpetofauna | 90.000 | 46.000 | 0.511 |
| Composition (Cm2) | Species richness of birds | 230.000 | 215.000 | 0.935 |
| Composition (Cm3) | Species richness of mammals | 46.000 | 31.000 | 0.674 |
| Structure (S1) | Aboveground biomass (Mg DM ha^-1^) | 187.234 | 152.051 | 0.812 |
| Structure (S2) | Forest canopy cover (%) | 72.000 | 60.000 | 0.833 |
:::

</details>