---
title: "Step 2. Condition indicators"
format: html
bibliography: references.bib
---

## Composition Indicators

The five indicators that were chosen were based on the data available from the baseline assessment of the area done for the corresponding VCS/CCB Project ([Project ID 3479](https://registry.verra.org/app/projectDetail/VCS/3479) IFM V0010). These are also important indicators for overall ecosystem health and function. The composition indicators that are used include 1) mammal species richness, 2) avian species richness, and 3) herpetofauna (amphibians and reptiles) species richness. The structure indicators that are used for the quantification include 4) aboveground biomass and 5) canopy cover, both suitable indicators to inform on ecosystem health and function.

### Mammal Species Richness

Mammal species richness is an appropriate indicator of biodiversity in sub-tropical dry forests as it is sensitive to habitat structure, resource availability, and anthropogenic pressures. Mammals occupy diverse ecological niches, and their presence often reflects overall ecosystem integrity, which serves as an effective proxy for measuring impacts of program activities on the environment [@ceballos2002]. Additionally, mammals are relatively easy to monitor through camera traps and transect surveys, which are easily replicable for monitoring over time, even in remote areas. Species richness is a simple analysis that can be done by basic training if communities are to take over on biodiversity monitoring.

Mammals were primarily monitored using camera traps that were placed in each ejido. The following pre-approved Standard Operating Procedure (SOP) was used in the nine ejidos. 10 Browing® Dark Ops APEX 20MP brand camera traps or similar equipment was placed, except for those ejidos in which there were logistics problems in the field and only 5 or 6 cameras were placed. Each camera trap was placed in a site with natural vegetation coverage and preferably at the intersection of 2 to 3 trails, they were attached to the base of the trunks at a height of 40 cm from the ground. The cameras were set to take a photo and a 15-second video, they remained active 24 hours a day for the duration of the study (2 weeks).

### Avian Species Richness

Bird species richness is an appropriate indicator for sub-tropical dry forests due to birds’ ecological sensitivity, habitat specificity, and functional diversity. The dry forests in the Project Extent are characterized by seasonal rainfall, deciduous vegetation, and high biodiversity, which allows for a wide array of bird species. Many of these species are habitat specialists or migratory species that rely on highly intact structure and seasonal resources. Birds respond quickly to changes in vegetation cover, forest structure and water availability, making them reliable early indicators of ecosystem health.

Program activities are aimed at improving forest structure through corridor development, conservation efforts, and increasing water availability in response to climate change. Changes in species richness over the program lifetime could be reliably attributed to changes due to program activities. Avian species were monitored with point counts along transects during the two week-long baseline biodiversity assessment conducted in 2023 using the pre-approved SOP. The following procedure was used to collect observations of avian species. The counting method was used by transects separated by 1 km between each transect. The criterion for choosing the transects was the proximity of the points where the camera traps were installed but separated at the beginning between 200 and 300 meters, so that the noise from the installation of the cameras would not affect the bird recording. The observation points were separated from each other every 100 m, at each point all the birds observed were recorded for 10 minutes.

### Herpetofauna Species Richness

Amphibians and reptiles are highly sensitive to changes in the environment. Reptiles (e.g., lizards, snakes, and turtles) are adapted to the warm, seasonally dry conditions characteristic of these forests. Many species are habitat specialists, occupying niches tied to particular vegetation types, ground cover, or thermal environments. Their population dynamics and community composition can change in response to alterations in land use, canopy cover, or fire regimes, making them effective indicators of habitat quality and connectivity. Amphibians, while generally associated with moist habitats, are also important in dry forests — especially those that rely on ephemeral water sources for reproduction. Their permeable skin makes them vulnerable to changes in temperature, humidity, water availability, and pollutants.

As a result, amphibians provide early warning signs of ecosystem degradation, particularly regarding hydrological balance and microhabitat integrity. Monitoring the richness of both groups captures complementary aspects of ecosystem health: reptiles reflect structural and thermal habitat features, while amphibians respond to moisture dynamics and microhabitat quality. Additionally, these taxa are often underrepresented in conservation assessments, so their inclusion supports a more holistic and taxonomically inclusive biodiversity strategy. It is important to note that monitoring did not occur during the wet season, when herpetofauna richness and diversity would be at its highest. Unfortunately, due to the remoteness of most of the ejidos and the transects, it is nearly impossible to navigate to some of them in the wet season. While it is not expected to observe the highest species richness each monitoring period, it is expected to see moderate richness and will provide a good indication of ecosystem health even in the dry season, when climate may be most impactful on the environment.

The following procedure, which is included in the pre-approved SOP for the Program, was used to monitor the herpetofauna species in the Project Extent. Transects of 1000 meters in length and 5 meters in width was chosen, during which a thorough search was carried out in all the microhabitats present within the transect, where the presence of herpetofauna was considered probable (under stones, under logs, in tree cavities, between tree bark, in burrows in the ground, etc.). The number of transects in each ejido varied depending on its area; the Program sought to cover the greatest heterogeneity of the landscape present in each locality. The lizards were captured using thick rubber bands, throwing them by stretching them with a finger and oriented towards the individual, so that when hitting them they produce a temporary immobilization that allows their capture without causing damage to the specimen.

The study was complemented by reviewing water sources and wells in those locations where there were bodies of water. The amphibians and reptiles found were identified to species level using specialized field guides and were recorded in a field log, along with the number of the specimen, the ejido where it was found, the number of the transect and any characteristic or observation of importance for this monitoring.

## Structure Indicators

### Aboveground biomass

Aboveground biomass is a widely used indicator for ecosystem structure, carbon storage, and habitat quality in subtropical dry forests. Aboveground biomass reflects the accumulation of woody materials (i.e., trees, shrubs), which influence the ecological functions and services of the ecosystem. In dry forest ecosystems, changes in AGB are related to land-use practices such as deforestation, grazing, and fuelwood extraction. Thus, monitoring AGB helps detect degradation and recovery over time, providing insight into the effectiveness of program activities (i.e., Assisted Native Regeneration in wildlife corridors, improved forest management). AGB is quantifiable through standardized field measurements and remote sensing, making it a practical and scalable indicator for monitoring ecosystem condition across large areas and over time.

### Canopy Cover

Canopy cover is a suitable indicator for subtropical dry forests because it reflects forest condition, habitat quality, and restoration progress. It influences microclimate, soil moisture, and biodiversity, particularly for forest-dependent species—and can be easily monitored using remote sensing or field tools. Its sensitivity to disturbance and recovery makes it a reliable measure of ecosystem health.
